# Generated by Django 3.2.8 on 2022-12-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.IntegerField()),
                ('dv', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('merchant_registration', models.CharField(blank=True, max_length=15, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.municipality')),
                ('type_documentI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.type_document_identification')),
                ('type_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.type_organization')),
                ('type_regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.type_regime')),
            ],
        ),
    ]
