# Generated by Django 3.2.8 on 2022-12-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.IntegerField(default=1),
        ),
    ]
