# Generated by Django 3.2.8 on 2022-12-08 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentI', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.CharField(max_length=20, unique=True)),
                ('psswd', models.CharField(max_length=20, unique=True)),
                ('block', models.BooleanField(default=False)),
                ('count_intent', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
