# Generated by Django 3.2.8 on 2022-12-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_count_intent_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Img_Profile'),
        ),
    ]
