# Generated by Django 3.2.8 on 2022-12-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_tpye_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='tpye_employee',
            new_name='type_employee',
        ),
    ]
