# Generated by Django 3.2.8 on 2023-02-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Close_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_total_box', models.FloatField(default=450000)),
                ('close_total_box', models.FloatField(default=0)),
                ('date_open', models.CharField(max_length=12)),
                ('date_close', models.CharField(max_length=12)),
                ('invoice_from', models.IntegerField(default=0)),
                ('invoice_to', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
