# Generated by Django 3.2.8 on 2023-02-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('close_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='close_box',
            name='cred',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='close_box',
            name='efec',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='close_box',
            name='payment_form',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='close_box',
            name='trans',
            field=models.FloatField(default=0),
        ),
    ]
