# Generated by Django 3.2.8 on 2022-12-15 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consecutive',
            new_name='Consecutive_FE',
        ),
        migrations.CreateModel(
            name='Consecutive_POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
