# Generated by Django 3.2.8 on 2023-01-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_consecutive_shopping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consecutive_Shopping',
        ),
    ]
