# Generated by Django 3.2.8 on 2022-12-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_type_client'),
        ('data', '0001_initial'),
        ('employee', '0003_remove_employee_count_intent_block'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.IntegerField()),
                ('code', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('tax', models.FloatField()),
                ('discount', models.FloatField()),
                ('quanty', models.FloatField()),
                ('date', models.CharField(max_length=10)),
                ('date_expired', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('cancelled', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.payment_form')),
            ],
        ),
    ]
