# Generated by Django 3.2.8 on 2022-12-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_wallet_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_pos',
            name='state',
            field=models.TextField(default='Factura Creada con éxito'),
        ),
    ]
