# Generated by Django 3.2.8 on 2023-03-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_salary'),
        ('pos', '0005_invoice_pos_type_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_pos',
            name='anulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet_pos',
            name='abono',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet_pos',
            name='employee_close',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_close', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='wallet_pos',
            name='payment_form',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice_pos',
            name='code',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='invoice_pos',
            name='type_sell',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
