# Generated by Django 3.2.8 on 2022-12-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone_2', models.CharField(max_length=20)),
                ('block', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution_POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=5)),
                ('resolution', models.IntegerField(max_length=12)),
                ('from_number', models.IntegerField(max_length=10)),
                ('date_from', models.CharField(max_length=10)),
                ('date_to', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Resolution_FE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=5)),
                ('resolution', models.IntegerField(max_length=12)),
                ('from_number', models.IntegerField(max_length=10)),
                ('date_from', models.CharField(max_length=10)),
                ('date_to', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('date_payment', models.CharField(max_length=12)),
                ('dete_experied', models.CharField(max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
