# Generated by Django 3.2.8 on 2023-01-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='document_annual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='license',
            name='employee',
            field=models.IntegerField(default=0),
        ),
    ]
