# Generated by Django 3.2.8 on 2023-01-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20230104_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='employee',
            field=models.IntegerField(default=1),
        ),
    ]
