# Generated by Django 3.2.8 on 2023-01-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20230104_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution_pos',
            name='token',
        ),
        migrations.AddField(
            model_name='resolution_fe',
            name='to_number',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='resolution_pos',
            name='to_number',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
