# Generated by Django 3.2.8 on 2022-12-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_wallet_fe_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_fe',
            name='state',
            field=models.TextField(default='Sin enviar a la DIAN'),
        ),
    ]
