# Generated by Django 3.2.8 on 2023-01-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20230104_1519'),
        ('employee', '0007_alter_employee_documenti'),
        ('invoice', '0007_invoice_fe_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_fe',
            name='cufe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='NoteCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('state', models.TextField(default='Sin enviar a la DIAN')),
                ('uuid', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice_fe')),
            ],
        ),
    ]
