# Generated by Django 3.2.8 on 2023-01-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20230104_1519'),
        ('shopping', '0002_rename_consecutive_shopping_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
